version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ecommerce-mongodb:/data/db
    command: "--noauth"  # Desactivar la autenticación (solo para pruebas)
volumes:
  ecommerce-mongodb:
